[package]
description = "blazingly fast revolutionary data structure"
name = "jitlist"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
dynasmrt = "5.0.0"

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "against_vec"
harness = false
